# Numpy

In [6]:
import numpy as np

In [8]:
list = [1, 3, 4, 5]
nplist = np.array(list)

nplist

array([1, 3, 4, 5])

In [13]:
list = np.array([[1, 3, 4], [5, 6, 7]]) 
list

array([[1, 3, 4],
       [5, 6, 7]])

In [14]:
list.shape

(2, 3)

In [26]:
list2 = np.arange(0, 70, 7)
list2

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63])

In [27]:
list2.reshape(2,5)
list2

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63])